### ISSUE TITLE
 item.onDidChangeSelectionRange is not a function

### ISSUE THREAD

**Issue by wafer-li** [nju33/atom-google-translate-modal#1]
### Steps to reproduce

Install from atom package manager

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [google-translate-modal](https://github.com/nju33/atom-google-translate-modal) package, v1.2.1

### Stack Trace

Failed to activate the google-translate-modal package

```
At item.onDidChangeSelectionRange is not a function

TypeError: item.onDidChangeSelectionRange is not a function
    at /Users/wafer/.atom/packages/google-translate-modal/lib/google-translate-modal.js:64:14
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:143:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:351:33)
    at Object.activate (/Users/wafer/.atom/packages/google-translate-modal/lib/google-translate-modal.js:53:43)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
 39x -5:34.8.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise.is-narrowed)
  6x -5:32.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise.is-narrowed)
  3x -5:31.7.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise.is-narrowed)
     -5:29.5.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise.is-narrowed)
     -5:21.5.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:16 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:12.4.0 core:paste (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -5:10.3.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -5:09.5.0 vim-mode-plus:put-after (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 15x -5:08.5.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -5:00.8.0 vim-mode-plus:insert-above-with-newline (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  6x -4:56.8.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode.autocomplete-active)
     -4:35 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -4:32.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:32.1.0 settings-view:open (atom-text-editor.editor.vim-mode-plus.insert-mode)
     -4:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-mdtoc, v0.8.3 (inactive)
autocomplete-emojis, v2.5.0 (active)
git-plus, v5.25.3 (active)
google-translate-modal, v1.2.1 (inactive)
language-latex, v1.0.0 (active)
language-plantuml, v0.2.0 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-enhanced, v0.8.9 (active)
markdown-writer, v2.6.2 (active)
plantuml, v0.1.2 (inactive)
plantuml-viewer, v0.7.1 (active)
project-manager, v3.3.3 (active)
vim-mode-plus, v0.66.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (active)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by nju33** [comment]
It's fixed in `v1.2.2`!
please update this. thanks ><b
